spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
  sql:
    init:
      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql
logging:
  level:
    org.springframework.jdbc: debug